
namespace SistemaManu
{
    partial class FrmNuevo
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmNuevo));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txtnombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtdireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txttelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtcorreo = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtfecha = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.btngenerar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtdepartamento = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtprovincia = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtdistrito = new Bunifu.UI.WinForms.BunifuTextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.btnUbigeo = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // labeltitulo
            // 
            this.labeltitulo.Location = new System.Drawing.Point(323, 9);
            this.labeltitulo.Size = new System.Drawing.Size(0, 24);
            this.labeltitulo.Text = "";
            // 
            // txtnombre
            // 
            this.txtnombre.AcceptsReturn = false;
            this.txtnombre.AcceptsTab = false;
            this.txtnombre.AnimationSpeed = 200;
            this.txtnombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnombre.BackColor = System.Drawing.Color.Transparent;
            this.txtnombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnombre.BackgroundImage")));
            this.txtnombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtnombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtnombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtnombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnombre.BorderRadius = 1;
            this.txtnombre.BorderThickness = 1;
            this.txtnombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtnombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtnombre.DefaultText = "";
            this.txtnombre.FillColor = System.Drawing.Color.White;
            this.txtnombre.HideSelection = true;
            this.txtnombre.IconLeft = null;
            this.txtnombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.IconPadding = 10;
            this.txtnombre.IconRight = null;
            this.txtnombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombre.Lines = new string[0];
            this.txtnombre.Location = new System.Drawing.Point(16, 25);
            this.txtnombre.MaxLength = 32767;
            this.txtnombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnombre.Modified = false;
            this.txtnombre.Multiline = false;
            this.txtnombre.Name = "txtnombre";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnombre.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombre.OnIdleState = stateProperties4;
            this.txtnombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtnombre.PasswordChar = '\0';
            this.txtnombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnombre.PlaceholderText = "Nombre y apellido";
            this.txtnombre.ReadOnly = false;
            this.txtnombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnombre.SelectedText = "";
            this.txtnombre.SelectionLength = 0;
            this.txtnombre.SelectionStart = 0;
            this.txtnombre.ShortcutsEnabled = true;
            this.txtnombre.Size = new System.Drawing.Size(260, 37);
            this.txtnombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnombre.TabIndex = 1;
            this.txtnombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnombre.TextMarginBottom = 0;
            this.txtnombre.TextMarginLeft = 3;
            this.txtnombre.TextMarginTop = 0;
            this.txtnombre.TextPlaceholder = "Nombre y apellido";
            this.txtnombre.UseSystemPasswordChar = false;
            this.txtnombre.WordWrap = true;
            // 
            // txtdireccion
            // 
            this.txtdireccion.AcceptsReturn = false;
            this.txtdireccion.AcceptsTab = false;
            this.txtdireccion.AnimationSpeed = 200;
            this.txtdireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtdireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtdireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtdireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtdireccion.BackgroundImage")));
            this.txtdireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtdireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtdireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtdireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtdireccion.BorderRadius = 1;
            this.txtdireccion.BorderThickness = 1;
            this.txtdireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtdireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtdireccion.DefaultText = "";
            this.txtdireccion.FillColor = System.Drawing.Color.White;
            this.txtdireccion.HideSelection = true;
            this.txtdireccion.IconLeft = null;
            this.txtdireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdireccion.IconPadding = 10;
            this.txtdireccion.IconRight = null;
            this.txtdireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdireccion.Lines = new string[0];
            this.txtdireccion.Location = new System.Drawing.Point(16, 77);
            this.txtdireccion.MaxLength = 32767;
            this.txtdireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtdireccion.Modified = false;
            this.txtdireccion.Multiline = false;
            this.txtdireccion.Name = "txtdireccion";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdireccion.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtdireccion.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdireccion.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdireccion.OnIdleState = stateProperties8;
            this.txtdireccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtdireccion.PasswordChar = '\0';
            this.txtdireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtdireccion.PlaceholderText = "Dirección";
            this.txtdireccion.ReadOnly = false;
            this.txtdireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtdireccion.SelectedText = "";
            this.txtdireccion.SelectionLength = 0;
            this.txtdireccion.SelectionStart = 0;
            this.txtdireccion.ShortcutsEnabled = true;
            this.txtdireccion.Size = new System.Drawing.Size(260, 37);
            this.txtdireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtdireccion.TabIndex = 2;
            this.txtdireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtdireccion.TextMarginBottom = 0;
            this.txtdireccion.TextMarginLeft = 3;
            this.txtdireccion.TextMarginTop = 0;
            this.txtdireccion.TextPlaceholder = "Dirección";
            this.txtdireccion.UseSystemPasswordChar = false;
            this.txtdireccion.WordWrap = true;
            // 
            // txttelefono
            // 
            this.txttelefono.AcceptsReturn = false;
            this.txttelefono.AcceptsTab = false;
            this.txttelefono.AnimationSpeed = 200;
            this.txttelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txttelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txttelefono.BackColor = System.Drawing.Color.Transparent;
            this.txttelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txttelefono.BackgroundImage")));
            this.txttelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txttelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txttelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txttelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txttelefono.BorderRadius = 1;
            this.txttelefono.BorderThickness = 1;
            this.txttelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txttelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txttelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txttelefono.DefaultText = "";
            this.txttelefono.FillColor = System.Drawing.Color.White;
            this.txttelefono.HideSelection = true;
            this.txttelefono.IconLeft = null;
            this.txttelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttelefono.IconPadding = 10;
            this.txttelefono.IconRight = null;
            this.txttelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txttelefono.Lines = new string[0];
            this.txttelefono.Location = new System.Drawing.Point(16, 135);
            this.txttelefono.MaxLength = 32767;
            this.txttelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txttelefono.Modified = false;
            this.txttelefono.Multiline = false;
            this.txttelefono.Name = "txttelefono";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttelefono.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txttelefono.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttelefono.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txttelefono.OnIdleState = stateProperties12;
            this.txttelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txttelefono.PasswordChar = '\0';
            this.txttelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txttelefono.PlaceholderText = "Teléfono";
            this.txttelefono.ReadOnly = false;
            this.txttelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txttelefono.SelectedText = "";
            this.txttelefono.SelectionLength = 0;
            this.txttelefono.SelectionStart = 0;
            this.txttelefono.ShortcutsEnabled = true;
            this.txttelefono.Size = new System.Drawing.Size(260, 37);
            this.txttelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txttelefono.TabIndex = 3;
            this.txttelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txttelefono.TextMarginBottom = 0;
            this.txttelefono.TextMarginLeft = 3;
            this.txttelefono.TextMarginTop = 0;
            this.txttelefono.TextPlaceholder = "Teléfono";
            this.txttelefono.UseSystemPasswordChar = false;
            this.txttelefono.WordWrap = true;
            // 
            // txtcorreo
            // 
            this.txtcorreo.AcceptsReturn = false;
            this.txtcorreo.AcceptsTab = false;
            this.txtcorreo.AnimationSpeed = 200;
            this.txtcorreo.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtcorreo.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtcorreo.BackColor = System.Drawing.Color.Transparent;
            this.txtcorreo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtcorreo.BackgroundImage")));
            this.txtcorreo.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtcorreo.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtcorreo.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtcorreo.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtcorreo.BorderRadius = 1;
            this.txtcorreo.BorderThickness = 1;
            this.txtcorreo.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtcorreo.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcorreo.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtcorreo.DefaultText = "";
            this.txtcorreo.FillColor = System.Drawing.Color.White;
            this.txtcorreo.HideSelection = true;
            this.txtcorreo.IconLeft = null;
            this.txtcorreo.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcorreo.IconPadding = 10;
            this.txtcorreo.IconRight = null;
            this.txtcorreo.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtcorreo.Lines = new string[0];
            this.txtcorreo.Location = new System.Drawing.Point(16, 190);
            this.txtcorreo.MaxLength = 32767;
            this.txtcorreo.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtcorreo.Modified = false;
            this.txtcorreo.Multiline = false;
            this.txtcorreo.Name = "txtcorreo";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcorreo.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtcorreo.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcorreo.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtcorreo.OnIdleState = stateProperties16;
            this.txtcorreo.Padding = new System.Windows.Forms.Padding(3);
            this.txtcorreo.PasswordChar = '\0';
            this.txtcorreo.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtcorreo.PlaceholderText = "Correo";
            this.txtcorreo.ReadOnly = false;
            this.txtcorreo.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtcorreo.SelectedText = "";
            this.txtcorreo.SelectionLength = 0;
            this.txtcorreo.SelectionStart = 0;
            this.txtcorreo.ShortcutsEnabled = true;
            this.txtcorreo.Size = new System.Drawing.Size(260, 37);
            this.txtcorreo.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtcorreo.TabIndex = 4;
            this.txtcorreo.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtcorreo.TextMarginBottom = 0;
            this.txtcorreo.TextMarginLeft = 3;
            this.txtcorreo.TextMarginTop = 0;
            this.txtcorreo.TextPlaceholder = "Correo";
            this.txtcorreo.UseSystemPasswordChar = false;
            this.txtcorreo.WordWrap = true;
            // 
            // txtfecha
            // 
            this.txtfecha.BackColor = System.Drawing.Color.Transparent;
            this.txtfecha.BorderRadius = 1;
            this.txtfecha.Color = System.Drawing.Color.Silver;
            this.txtfecha.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.txtfecha.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.txtfecha.DisabledColor = System.Drawing.Color.Gray;
            this.txtfecha.DisplayWeekNumbers = false;
            this.txtfecha.DPHeight = 0;
            this.txtfecha.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.txtfecha.FillDatePicker = false;
            this.txtfecha.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtfecha.ForeColor = System.Drawing.Color.Black;
            this.txtfecha.Icon = ((System.Drawing.Image)(resources.GetObject("txtfecha.Icon")));
            this.txtfecha.IconColor = System.Drawing.Color.Gray;
            this.txtfecha.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.txtfecha.LeftTextMargin = 5;
            this.txtfecha.Location = new System.Drawing.Point(16, 254);
            this.txtfecha.MinimumSize = new System.Drawing.Size(4, 32);
            this.txtfecha.Name = "txtfecha";
            this.txtfecha.Size = new System.Drawing.Size(220, 32);
            this.txtfecha.TabIndex = 5;
            // 
            // btngenerar
            // 
            this.btngenerar.AllowAnimations = true;
            this.btngenerar.AllowMouseEffects = true;
            this.btngenerar.AllowToggling = false;
            this.btngenerar.AnimationSpeed = 200;
            this.btngenerar.AutoGenerateColors = false;
            this.btngenerar.AutoRoundBorders = false;
            this.btngenerar.AutoSizeLeftIcon = true;
            this.btngenerar.AutoSizeRightIcon = true;
            this.btngenerar.BackColor = System.Drawing.Color.Transparent;
            this.btngenerar.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btngenerar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btngenerar.BackgroundImage")));
            this.btngenerar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btngenerar.ButtonText = "Generar documento";
            this.btngenerar.ButtonTextMarginLeft = 0;
            this.btngenerar.ColorContrastOnClick = 45;
            this.btngenerar.ColorContrastOnHover = 45;
            this.btngenerar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btngenerar.CustomizableEdges = borderEdges1;
            this.btngenerar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btngenerar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btngenerar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btngenerar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btngenerar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btngenerar.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btngenerar.ForeColor = System.Drawing.Color.White;
            this.btngenerar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btngenerar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btngenerar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btngenerar.IconMarginLeft = 11;
            this.btngenerar.IconPadding = 10;
            this.btngenerar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btngenerar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btngenerar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btngenerar.IconSize = 25;
            this.btngenerar.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btngenerar.IdleBorderRadius = 1;
            this.btngenerar.IdleBorderThickness = 1;
            this.btngenerar.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btngenerar.IdleIconLeftImage = null;
            this.btngenerar.IdleIconRightImage = null;
            this.btngenerar.IndicateFocus = false;
            this.btngenerar.Location = new System.Drawing.Point(177, 388);
            this.btngenerar.Name = "btngenerar";
            this.btngenerar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btngenerar.OnDisabledState.BorderRadius = 1;
            this.btngenerar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btngenerar.OnDisabledState.BorderThickness = 1;
            this.btngenerar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btngenerar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btngenerar.OnDisabledState.IconLeftImage = null;
            this.btngenerar.OnDisabledState.IconRightImage = null;
            this.btngenerar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btngenerar.onHoverState.BorderRadius = 1;
            this.btngenerar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btngenerar.onHoverState.BorderThickness = 1;
            this.btngenerar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btngenerar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btngenerar.onHoverState.IconLeftImage = null;
            this.btngenerar.onHoverState.IconRightImage = null;
            this.btngenerar.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btngenerar.OnIdleState.BorderRadius = 1;
            this.btngenerar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btngenerar.OnIdleState.BorderThickness = 1;
            this.btngenerar.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btngenerar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btngenerar.OnIdleState.IconLeftImage = null;
            this.btngenerar.OnIdleState.IconRightImage = null;
            this.btngenerar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btngenerar.OnPressedState.BorderRadius = 1;
            this.btngenerar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btngenerar.OnPressedState.BorderThickness = 1;
            this.btngenerar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btngenerar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btngenerar.OnPressedState.IconLeftImage = null;
            this.btngenerar.OnPressedState.IconRightImage = null;
            this.btngenerar.Size = new System.Drawing.Size(150, 39);
            this.btngenerar.TabIndex = 6;
            this.btngenerar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btngenerar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btngenerar.TextMarginLeft = 0;
            this.btngenerar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btngenerar.UseDefaultRadiusAndThickness = true;
            this.btngenerar.Click += new System.EventHandler(this.btngenerar_Click_1);
            // 
            // txtdepartamento
            // 
            this.txtdepartamento.AcceptsReturn = false;
            this.txtdepartamento.AcceptsTab = false;
            this.txtdepartamento.AnimationSpeed = 200;
            this.txtdepartamento.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtdepartamento.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtdepartamento.BackColor = System.Drawing.Color.Transparent;
            this.txtdepartamento.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtdepartamento.BackgroundImage")));
            this.txtdepartamento.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtdepartamento.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtdepartamento.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtdepartamento.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtdepartamento.BorderRadius = 1;
            this.txtdepartamento.BorderThickness = 1;
            this.txtdepartamento.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtdepartamento.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdepartamento.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtdepartamento.DefaultText = "";
            this.txtdepartamento.FillColor = System.Drawing.Color.White;
            this.txtdepartamento.HideSelection = true;
            this.txtdepartamento.IconLeft = null;
            this.txtdepartamento.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdepartamento.IconPadding = 10;
            this.txtdepartamento.IconRight = null;
            this.txtdepartamento.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdepartamento.Lines = new string[0];
            this.txtdepartamento.Location = new System.Drawing.Point(36, 174);
            this.txtdepartamento.MaxLength = 32767;
            this.txtdepartamento.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtdepartamento.Modified = false;
            this.txtdepartamento.Multiline = false;
            this.txtdepartamento.Name = "txtdepartamento";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdepartamento.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtdepartamento.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdepartamento.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdepartamento.OnIdleState = stateProperties20;
            this.txtdepartamento.Padding = new System.Windows.Forms.Padding(3);
            this.txtdepartamento.PasswordChar = '\0';
            this.txtdepartamento.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtdepartamento.PlaceholderText = "Departamento";
            this.txtdepartamento.ReadOnly = false;
            this.txtdepartamento.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtdepartamento.SelectedText = "";
            this.txtdepartamento.SelectionLength = 0;
            this.txtdepartamento.SelectionStart = 0;
            this.txtdepartamento.ShortcutsEnabled = true;
            this.txtdepartamento.Size = new System.Drawing.Size(260, 37);
            this.txtdepartamento.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtdepartamento.TabIndex = 9;
            this.txtdepartamento.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtdepartamento.TextMarginBottom = 0;
            this.txtdepartamento.TextMarginLeft = 3;
            this.txtdepartamento.TextMarginTop = 0;
            this.txtdepartamento.TextPlaceholder = "Departamento";
            this.txtdepartamento.UseSystemPasswordChar = false;
            this.txtdepartamento.WordWrap = true;
            // 
            // txtprovincia
            // 
            this.txtprovincia.AcceptsReturn = false;
            this.txtprovincia.AcceptsTab = false;
            this.txtprovincia.AnimationSpeed = 200;
            this.txtprovincia.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtprovincia.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtprovincia.BackColor = System.Drawing.Color.Transparent;
            this.txtprovincia.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtprovincia.BackgroundImage")));
            this.txtprovincia.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtprovincia.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtprovincia.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtprovincia.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtprovincia.BorderRadius = 1;
            this.txtprovincia.BorderThickness = 1;
            this.txtprovincia.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtprovincia.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtprovincia.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtprovincia.DefaultText = "";
            this.txtprovincia.FillColor = System.Drawing.Color.White;
            this.txtprovincia.HideSelection = true;
            this.txtprovincia.IconLeft = null;
            this.txtprovincia.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtprovincia.IconPadding = 10;
            this.txtprovincia.IconRight = null;
            this.txtprovincia.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtprovincia.Lines = new string[0];
            this.txtprovincia.Location = new System.Drawing.Point(36, 119);
            this.txtprovincia.MaxLength = 32767;
            this.txtprovincia.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtprovincia.Modified = false;
            this.txtprovincia.Multiline = false;
            this.txtprovincia.Name = "txtprovincia";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtprovincia.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtprovincia.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtprovincia.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtprovincia.OnIdleState = stateProperties24;
            this.txtprovincia.Padding = new System.Windows.Forms.Padding(3);
            this.txtprovincia.PasswordChar = '\0';
            this.txtprovincia.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtprovincia.PlaceholderText = "Provincia";
            this.txtprovincia.ReadOnly = false;
            this.txtprovincia.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtprovincia.SelectedText = "";
            this.txtprovincia.SelectionLength = 0;
            this.txtprovincia.SelectionStart = 0;
            this.txtprovincia.ShortcutsEnabled = true;
            this.txtprovincia.Size = new System.Drawing.Size(260, 37);
            this.txtprovincia.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtprovincia.TabIndex = 8;
            this.txtprovincia.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtprovincia.TextMarginBottom = 0;
            this.txtprovincia.TextMarginLeft = 3;
            this.txtprovincia.TextMarginTop = 0;
            this.txtprovincia.TextPlaceholder = "Provincia";
            this.txtprovincia.UseSystemPasswordChar = false;
            this.txtprovincia.WordWrap = true;
            // 
            // txtdistrito
            // 
            this.txtdistrito.AcceptsReturn = false;
            this.txtdistrito.AcceptsTab = false;
            this.txtdistrito.AnimationSpeed = 200;
            this.txtdistrito.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtdistrito.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtdistrito.BackColor = System.Drawing.Color.Transparent;
            this.txtdistrito.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtdistrito.BackgroundImage")));
            this.txtdistrito.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtdistrito.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtdistrito.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtdistrito.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtdistrito.BorderRadius = 1;
            this.txtdistrito.BorderThickness = 1;
            this.txtdistrito.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtdistrito.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdistrito.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtdistrito.DefaultText = "";
            this.txtdistrito.FillColor = System.Drawing.Color.White;
            this.txtdistrito.HideSelection = true;
            this.txtdistrito.IconLeft = null;
            this.txtdistrito.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdistrito.IconPadding = 10;
            this.txtdistrito.IconRight = null;
            this.txtdistrito.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtdistrito.Lines = new string[0];
            this.txtdistrito.Location = new System.Drawing.Point(36, 61);
            this.txtdistrito.MaxLength = 32767;
            this.txtdistrito.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtdistrito.Modified = false;
            this.txtdistrito.Multiline = false;
            this.txtdistrito.Name = "txtdistrito";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdistrito.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtdistrito.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdistrito.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtdistrito.OnIdleState = stateProperties28;
            this.txtdistrito.Padding = new System.Windows.Forms.Padding(3);
            this.txtdistrito.PasswordChar = '\0';
            this.txtdistrito.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtdistrito.PlaceholderText = "Distrito";
            this.txtdistrito.ReadOnly = false;
            this.txtdistrito.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtdistrito.SelectedText = "";
            this.txtdistrito.SelectionLength = 0;
            this.txtdistrito.SelectionStart = 0;
            this.txtdistrito.ShortcutsEnabled = true;
            this.txtdistrito.Size = new System.Drawing.Size(260, 37);
            this.txtdistrito.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtdistrito.TabIndex = 7;
            this.txtdistrito.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtdistrito.TextMarginBottom = 0;
            this.txtdistrito.TextMarginLeft = 3;
            this.txtdistrito.TextMarginTop = 0;
            this.txtdistrito.TextPlaceholder = "Distrito";
            this.txtdistrito.UseSystemPasswordChar = false;
            this.txtdistrito.WordWrap = true;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.btnUbigeo);
            this.groupBox1.Controls.Add(this.txtprovincia);
            this.groupBox1.Controls.Add(this.txtdepartamento);
            this.groupBox1.Controls.Add(this.txtdistrito);
            this.groupBox1.Location = new System.Drawing.Point(333, 160);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(317, 222);
            this.groupBox1.TabIndex = 10;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Ubigeo de la Dirección";
            // 
            // btnUbigeo
            // 
            this.btnUbigeo.AllowAnimations = true;
            this.btnUbigeo.AllowMouseEffects = true;
            this.btnUbigeo.AllowToggling = false;
            this.btnUbigeo.AnimationSpeed = 200;
            this.btnUbigeo.AutoGenerateColors = false;
            this.btnUbigeo.AutoRoundBorders = false;
            this.btnUbigeo.AutoSizeLeftIcon = true;
            this.btnUbigeo.AutoSizeRightIcon = true;
            this.btnUbigeo.BackColor = System.Drawing.Color.Transparent;
            this.btnUbigeo.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnUbigeo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUbigeo.BackgroundImage")));
            this.btnUbigeo.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUbigeo.ButtonText = ":::";
            this.btnUbigeo.ButtonTextMarginLeft = 0;
            this.btnUbigeo.ColorContrastOnClick = 45;
            this.btnUbigeo.ColorContrastOnHover = 45;
            this.btnUbigeo.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnUbigeo.CustomizableEdges = borderEdges2;
            this.btnUbigeo.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUbigeo.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUbigeo.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUbigeo.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUbigeo.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUbigeo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnUbigeo.ForeColor = System.Drawing.Color.White;
            this.btnUbigeo.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUbigeo.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUbigeo.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUbigeo.IconMarginLeft = 11;
            this.btnUbigeo.IconPadding = 10;
            this.btnUbigeo.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUbigeo.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUbigeo.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUbigeo.IconSize = 25;
            this.btnUbigeo.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnUbigeo.IdleBorderRadius = 1;
            this.btnUbigeo.IdleBorderThickness = 1;
            this.btnUbigeo.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnUbigeo.IdleIconLeftImage = null;
            this.btnUbigeo.IdleIconRightImage = null;
            this.btnUbigeo.IndicateFocus = false;
            this.btnUbigeo.Location = new System.Drawing.Point(204, 19);
            this.btnUbigeo.Name = "btnUbigeo";
            this.btnUbigeo.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUbigeo.OnDisabledState.BorderRadius = 1;
            this.btnUbigeo.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUbigeo.OnDisabledState.BorderThickness = 1;
            this.btnUbigeo.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUbigeo.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUbigeo.OnDisabledState.IconLeftImage = null;
            this.btnUbigeo.OnDisabledState.IconRightImage = null;
            this.btnUbigeo.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUbigeo.onHoverState.BorderRadius = 1;
            this.btnUbigeo.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUbigeo.onHoverState.BorderThickness = 1;
            this.btnUbigeo.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUbigeo.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUbigeo.onHoverState.IconLeftImage = null;
            this.btnUbigeo.onHoverState.IconRightImage = null;
            this.btnUbigeo.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnUbigeo.OnIdleState.BorderRadius = 1;
            this.btnUbigeo.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUbigeo.OnIdleState.BorderThickness = 1;
            this.btnUbigeo.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnUbigeo.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUbigeo.OnIdleState.IconLeftImage = null;
            this.btnUbigeo.OnIdleState.IconRightImage = null;
            this.btnUbigeo.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUbigeo.OnPressedState.BorderRadius = 1;
            this.btnUbigeo.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUbigeo.OnPressedState.BorderThickness = 1;
            this.btnUbigeo.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUbigeo.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUbigeo.OnPressedState.IconLeftImage = null;
            this.btnUbigeo.OnPressedState.IconRightImage = null;
            this.btnUbigeo.Size = new System.Drawing.Size(70, 36);
            this.btnUbigeo.TabIndex = 11;
            this.btnUbigeo.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUbigeo.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUbigeo.TextMarginLeft = 0;
            this.btnUbigeo.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUbigeo.UseDefaultRadiusAndThickness = true;
            this.btnUbigeo.Click += new System.EventHandler(this.btnUbigeo_Click);
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.txtnombre);
            this.groupBox2.Controls.Add(this.txtdireccion);
            this.groupBox2.Controls.Add(this.txttelefono);
            this.groupBox2.Controls.Add(this.txtfecha);
            this.groupBox2.Controls.Add(this.txtcorreo);
            this.groupBox2.Location = new System.Drawing.Point(26, 79);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(301, 303);
            this.groupBox2.TabIndex = 11;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Datos de la empresa";
            // 
            // FrmNuevo
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(675, 449);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.btngenerar);
            this.Name = "FrmNuevo";
            this.Text = "FrmNuevo";
            this.Load += new System.EventHandler(this.FrmNuevo_Load);
            this.Controls.SetChildIndex(this.btngenerar, 0);
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox txtnombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtdireccion;
        private Bunifu.UI.WinForms.BunifuTextBox txttelefono;
        private Bunifu.UI.WinForms.BunifuTextBox txtcorreo;
        private Bunifu.UI.WinForms.BunifuDatePicker txtfecha;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btngenerar;
        private Bunifu.UI.WinForms.BunifuTextBox txtdepartamento;
        private Bunifu.UI.WinForms.BunifuTextBox txtprovincia;
        private Bunifu.UI.WinForms.BunifuTextBox txtdistrito;
        private System.Windows.Forms.GroupBox groupBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUbigeo;
        private System.Windows.Forms.GroupBox groupBox2;
    }
}